### ISSUE TITLE
Copy Trait is not Implemented for CreateDelta

### ISSUE THREAD

**Issue by MarkintoshZ** [chinedufn/dipa#6]
A common pattern in game server is broadcasting the change in game state to every client as shown in the following example:
```rust
for client in &clients {
    client.send(CreateDelta<GameState>.clone())?;
}
```
The problem is that the ```CreateDelta``` struct does not implement the ```Clone``` trait.
Is there a reason why the ```Clone``` trait is not implemented? If so, what would be the proper way of handling such case?

Thanks a lot! :)

**Comment by chinedufn** [comment]
Hey!

There isn't a particular reason, so if there is a good reason to add `Clone` we can.

I think that a game would want to avoid unnecessary copies though, so I only want to add these bounds if they are necessary.

---

It sounds like in your case you're sending the same exact state to many clients?

---

Are you sending the data over a network? If you, I'd imagine you'd want to

1. Serialize state into bytes `Vec<u8>`
2. Send those bytes over the network to each client, without cloning.

i.e. something like:

```rust
let bytes: Vec<u8> = serialize_my_state(&game_state);
for client in &clients {
    client.send(&bytes);
}
```

---

If you truly needed to clone you could just do it yourself.

```rust
let state: CreatedDelta<GameState> = get_delta();
let state_cloned = CreatedDelta {
    delta: state.delta.clone(),
    did_change: state.delta.did_change
}
```

---

So yeah.. If your use case truly _requires_ cloning then I'm happy to add a Clone impl.

If it doesn't require it then I'd prefer to avoid the impl and instead encourage people to avoid cloning.

I'd love to hear more details about whether or not this helps with your use case.

Cheers!

**Comment by MarkintoshZ** [comment]
Hi!

My use case does require me to clone the delta but I didn't realize I can construct the clone on my own. That solves all the problem! Thanks a lot!

I'll close the issue now!
