### ISSUE TITLE
Handling external structs

### ISSUE THREAD

**Issue by AndrewJSchoen** [chinedufn/dipa#7]
First of all, thanks for the library! 

I am using an external library's struct (`uuid`) in some of my own structs. The `uuid` library supports serialization features, but by default doesn't have implementations for anything like this library. Is there a straightforward way of defining how the `Uuid` struct gets handled within `dipa` from the struct specification of my enclosing struct in the derivation, (e.g. avoiding custom implementations for all affected structs)?

Thanks!

**Comment by chinedufn** [comment]
Hey.

You can use a new type wrapper.

```rust
struct MyUuidWrapper(uuid::Uuid);

impl<'s, 'e> Diffable<'s, 'e, DeltaWithI8> for MyUuidWrapper {
    // ...
}

impl Patchable<i8> for MyUuidWrapper {
    // ...
}

// ... Optional for convenience ...
// impl Deref for MyUuidWrapper {
//     type Target = uuid::Uuid;
// 
//     fn deref(&self) -> &Self::Target {
//         &self.0
//     }
// }
```

Then in your structs you can use `MyUuidWrapper` instead of `uuid::Uuid`.

```rust
#[derive(DiffPatch)]
struct MyStructA {
    id: MyUuidWrapper
}

#[derive(DiffPatch)]
struct MyStructB {
    id: MyUuidWrapper
}
```


I'll close this out. Please re-open if that answer does not help in your case.
